# Generated by Django 2.2.5 on 2019-10-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='type',
            field=models.CharField(default='police', max_length=64),
        ),
    ]
